site_name: ML Dataset Sustainability Toolkit

theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    # - toc.integrate
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue grey
      accent: indigo
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: indigo

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

#page tree
nav:
  - Home: index.md
  - Getting started:
    - Introduction: definition.md
    - Fair Principles: fair.md
  - Before Publishing: 
    - Produce High Quality Datasets: beforepublish.md
    - Create Privacy-Preserving Datasets: privacy.md
    - Document your Datasets Extensively: documentation.md
  - Hosting your Datasets: hosting.md
  - After Publishing:
    - Promoting Discoverability and Reuse: discoverability.md
    - Ethical Considerations: ethicalAI.md
    - Funding your Project: funding.md
  - TL;DR: TL;DR.md
